### PR TITLE
Prepare Automatic Releases: add commitlint, renovate, and semantic-release

### PR DESCRIPTION
**Pull request by NullVoxPopuli**

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
@lifeart, looks like there is an upstream type error?
```
src/definition-providers/template.ts:70:17 - error TS2742: The inferred type of 'provideRouteDefinition' cannot be named without a reference to '@emberwatch/ember-language-server/node_modules/vscode-languageserver-types'. This is likely not portable. A type annotation is necessary.

70 export function provideRouteDefinition(root: string, routeName: string) {
                   ~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by lifeart** [comment]
hm, strange, can't catch with issue during compilation / development
image


is it compiled under another root?

**Comment by NullVoxPopuli** [comment]
that happens during `yarn install`... which I don't understand why ther'd even be a lint error. Unless the language server has some `postinstall` hook?

These are the only scripts I have: 
 - update-language-server
 - clean
 - build:js
 - build:language-server
 - build:bandle-language-server
 - lint:js
 - prepublish

**Comment by lifeart** [comment]
Can't find any postinstalls - https://github.com/lifeart/ember-language-server/blob/component-context-info-origin/package.json (( Is ts versions same for project & langserver?

**Comment by NullVoxPopuli** [comment]
looks like this is running during install:
```
$ npx npm-run-all clean build:js build:language-server build:bundle-language-server
```
which is my prepublish script... wat

**Comment by NullVoxPopuli** [comment]
looks like maybe this is what I needed? https://github.com/video-dev/can-autoplay/pull/15/files

**Comment by NullVoxPopuli** [comment]
@lifeart trying to figure out how to release now, and it looks like when I run `compile` I get the type error. why does this happen?
are there types private to the project?

**Comment by NullVoxPopuli** [comment]
it's this command that fails:
```
 cd node_modules/@emberwatch/ember-language-server && yarn
```

**Comment by NullVoxPopuli** [comment]
and yes, we have the same TS version

**Comment by NullVoxPopuli** [comment]
I think I figured it out. latest commit on master has the fix: https://github.com/NullVoxPopuli/coc-ember/commit/d61f01eaced6c0e6fa23fbcee949e5de7943f59e

**Pull request merged**
